import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MobileNavBar from "@/components/mobile-nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <MobileNavBar />
      </body>
    </html>
  );
}
